name: Node.js Package

on:
  push:
    branches:
      - main  # 👈 确保这里改成了 main

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # 升级到 v4
      - uses: actions/setup-node@v4 # 升级到 v4
        with:
          node-version: "18.x"     # 推荐使用较新的 LTS 版本 Node
          registry-url: https://registry.npmjs.org/
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
