name: Node.js Package

on:
  push:
    branches:
      - main

# 必须添加以下权限，以便与 npm 进行 OIDC 认证
permissions:
  contents: read
  id-token: write

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          registry-url: https://registry.npmjs.org/
      
      # 此时直接运行 publish，npm 会自动识别 GitHub 提供的身份凭证，无需传入 Token 或 OTP
      - run: npm publish --provenance
