name: Node.js Package

on:
  push:
    branches:
      - main

# 1. 必须声明此权限，允许向 npm 申请 OIDC 临时证书
permissions:
  contents: read
  id-token: write

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          # 2. 必须保留此行！它告诉 setup-node 将 npm 配置指向官方源，从而激活 OIDC 认证机制
          registry-url: "https://registry.npmjs.org/"
          
      # 3. 运行发布。千万不要配置 env: NODE_AUTH_TOKEN
      # --provenance 参数是可选的，用于生成构建来源证明
      - run: npm publish --provenance
